version: '2.11'
services:
  # PHP container
  php:
    container_name: eshop-app
    restart: always
    depends_on:
      keyrock-db:
        condition: service_healthy 
      # keyrock:
      #   condition: service_started
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    ports:
      - '8000:8000'
    

  #MySQL Database container
  # app-db:
  #   container_name: application-db
  #   image: mysql:8.0
  #   cap_add:
  #       - SYS_NICE
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=${DB_DATABASE}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - '52000:3306'
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #     - ./db/eshop.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
  #     start_period: 5s
  #     interval: 5s
  #     timeout: 5s
  #     retries: 55

# Keyrock is an Identity Management Service
  keyrock:
    labels:
      org.fiware: 'tutorial'
    image: fiware/idm:${KEYROCK_VERSION}
    container_name: fiware-keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      keyrock-db:
        condition:  service_healthy
    ports:
      - "${KEYROCK_PORT}:${KEYROCK_PORT}" # localhost:3005
      - "${KEYROCK_HTTPS_PORT}:${KEYROCK_HTTPS_PORT}" # localhost:3443
    environment:
      - "DEBUG=idm:*"
      - "IDM_DB_HOST=keyrock-db"
      - "IDM_DB_PASS=secret"
      - "IDM_DB_USER=root"
      - "IDM_PORT=${KEYROCK_PORT}"
      - "IDM_HOST=http://localhost:${KEYROCK_PORT}"
      - "IDM_ADMIN_USER=admin"
      - "IDM_ADMIN_EMAIL=admin@test.com"
      - "IDM_ADMIN_PASS=1234"
      - IDM_CSP_FORM_ACTION=*
    healthcheck:
      interval: 5s

  # Database
  keyrock-db:
    restart: always
    labels:
      org.fiware: 'tutorial'
    image: mysql:8.0
    hostname: keyrock-db
    container_name: db-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      - "MYSQL_DATABASE=idm"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=%" # Allow Keyrock to access this database
    volumes:
      - ./idm_data:/var/lib/mysql
      - ./db/idm.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=secret
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
    






      
    